########################
# HTTP server settings #
########################
port: 8000
listen_address: "0.0.0.0"
cors_allow_origins: ["*"]

####################
# General settings #
####################
allow_reset: true
